import numpy as np
import os
import matplotlib.image as Image
from matplotlib import pyplot as plt

def display():
    image = Image.imread('Figure_1.png')
    plt.subplot(331)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_1 0:00:03")
    image = Image.imread('Figure_2.png')
    plt.subplot(332)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_2 0:00:06")
    image = Image.imread('Figure_3.png')
    plt.subplot(333)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_3  0:00:09")
    image = Image.imread('Figure_4.png')
    plt.subplot(334)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_4  0:00:12")
    image = Image.imread('Figure_5.png')
    plt.subplot(335)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_5  0:00:15")
    image = Image.imread('Figure_6.png')
    plt.subplot(336)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_6  0:00:18")
    image = Image.imread('Figure_7.png')
    plt.subplot(337)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_7  0:00:21")
    image = Image.imread('Figure_8.png')
    plt.subplot(338)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_8  0:00:24")
    image = Image.imread('Figure_9.png')
    plt.subplot(339)
    plt.axis('off')
    plt.imshow(image)
    plt.title("Figure_9  0:00:27")
    plt.show()

if __name__ == "__main__":
    print("display")
    display()